---
k3s_version: v1.36.2+k3s1
k3s_cluster_interface: eth0
k3s_admin_interface: wlan0
k3s_cluster_cidr: 10.42.0.0/16
k3s_service_cidr: 10.43.0.0/16
k3s_cluster_domain: cluster.local
k3s_controller_admin_endpoint: dkhundley-homelab-controller.local
k3s_kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/k3s-homelab.yaml"
k3s_installer_url: https://get.k3s.io
k3s_disabled_components:
  - traefik
  - servicelb

kubelet_eviction_hard:
  memory.available: 512Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
  imagefs.available: 10%
  imagefs.inodesFree: 5%
kubelet_eviction_minimum_reclaim:
  nodefs.available: 10%
  imagefs.available: 10%

k3s_required_packages:
  - ca-certificates
  - curl
  - jq
  - network-manager
  - openssl
  - python3
  - rpi-eeprom

